### ISSUE TITLE
Django 3.0 Support

### ISSUE THREAD

**Issue by atlasstrategic** [pjdelport/django-payfast#14]
Django 3.0 [removes](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis) `django.utils.encoding.python_2_unicode_compatible()`, which is used as a [decorator](https://github.com/PiDelport/django-payfast/blob/9c14aec3d3993644464c1cdacc89614500de664d/payfast/models.py#L11) on the `PayFastOrder` model.

Removing this decorator is required for Django 3.0 support.

## Reference
- https://github.com/macropin/django-registration/issues/371

**Comment by qoda** [comment]
Any chance @atlasstrategic fix can be merged, I'm seeing the same issue on my side, using Django 3.0.6:

```
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "-/ve/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "-/ve/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "-/ve/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "-/ve/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "-/ve/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "-/ve/lib/python3.7/site-packages/payfast/models.py", line 6, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (-/ve/lib/python3.7/site-packages/django/utils/encoding.py)
```

**Comment by Moon-developer** [comment]
Is this project going to be updated for Django 3 by any chance?

**Comment by sirthom9123** [comment]
This project is old, came across a number of errors. Is this gonna be fixed in Django 3? Or can I contribute?
